#basic makefile

var := 15/1/2026

print_hello1: 
	@echo "Hello Makefile"

include abc.mk

print_hello2: print_hello1
	@echo "Hello Embedded Software; k; \
		GCC Build"

variable:
	@echo "gia tri value: $(var)"
